parameters:
     angle.mobile_detector.class: Angle\Common\MobileDetectBundle\DeviceDetector\MobileDetector

services:
     angle.mobile_detector:
         class:     %angle.mobile_detector.class%
         arguments: [ ]